server:
  port: 9090
  
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/ba25/chauffeur/-/tree/master/config-repo
          username: bhanureddypadhira
          passphrase: Bhanu@1105
          search-paths:
          - '*service'
